### ISSUE TITLE
Socket disconnects immediately after connect on iOS.

### ISSUE THREAD

**Issue by vladpre92** [naderio/nativescript-socket.io#1]
Hello.
I found a bug while playing with nativescript-socket.io, and I can't find a solution. 
Every connection event to socket.io server from an iOS device, is followed by an 'disconnect event'. Every time.
It seems I get a Bad Request Error.
On Android devices works fine.
How can I solve this problem? Thanks!

**Comment by naderio** [comment]
hello @vladpre92,
iOS is not usable as is, and still in development.
nevertheless, I've managed to establish a sable connection with the plugin, otherwise nothing else can be done for now (listening, emitting events, ...)

**Comment by facekapow** [comment]
Hi, I'm also having a similar issue. I haven't managed to debug, so I can't verify whether this is the case, but trying to connect to the server (or possibly it's checking `socket.connected`, I'm not sure) cause the app to freeze on iOS (both in the emulator and on my iPad), on Android it works perfectly.

**Comment by girishgkg** [comment]
We are also facing the same problem,i have pasted the logs as well.

Starting iOS Simulator
Jun 30 18:19:45 imac backboardd[1570]: SecTaskCopyDebugDescription: demo[4352]
Jun 30 18:19:45 imac backboardd[1570]: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
Jun 30 18:19:45 imac backboardd[1570]: SecTaskCopyDebugDescription: demo[4352]
Jun 30 18:19:45 imac backboardd[1570]: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
Jun 30 18:19:45 imac backboardd[1570]: SecTaskCopyDebugDescription: demo[4352]
Jun 30 18:19:45 imac backboardd[1570]: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
Jun 30 18:19:45 imac backboardd[1570]: SecTaskCopyDebugDescription: demo[4352]
Jun 30 18:19:45 imac backboardd[1570]: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
Jun 30 18:19:45 imac backboardd[1570]: SecTaskCopyDebugDescription: demo[4352]
Jun 30 18:19:45 imac demo[4352]: assertion failed: 15E65 13E230: libxpc.dylib + 71506 [6F98A9DA-B46E-3A2B-88D4-92F1EC77477F]: 0x7d
Jun 30 18:19:45 imac demo[4352]: LOG SocketIOClient: Adding engine
Jun 30 18:19:45 imac demo[4352]: LOG SocketEngine: Starting engine. Server: http://192.168.2.14:3210
Jun 30 18:19:45 imac demo[4352]: LOG SocketEngine: Handshaking
Jun 30 18:19:45 imac demo[4352]: LOG SocketEngine: Got message: 0{"sid":"7wkqNeCdRVCjxM4OAAAA","upgrades":[],"pingInterval":2000,"pingTimeout":60000}
Jun 30 18:19:45 imac demo[4352]: LOG SocketEngine: Writing ws:  has data: 0
Jun 30 18:19:45 imac demo[4352]: LOG SocketEngine: Sending ws:  as type: 2
Jun 30 18:19:45 imac demo[4352]: LOG SocketEngineClient: Connect
Jun 30 18:19:45 imac demo[4352]: LOG SocketEngine: Got message: 40
Jun 30 18:19:45 imac demo[4352]: LOG SocketIOClient: Should parse message: 0
Jun 30 18:19:45 imac demo[4352]: LOG SocketParser: Parsing 0
Jun 30 18:19:45 imac demo[4352]: LOG SocketParser: Decoded packet as: SocketPacket {type: 0; data: []; id: -1; placeholders: 0; nsp: /}
Jun 30 18:19:45 imac demo[4352]: LOG SocketIOClient: Socket connected
Jun 30 18:19:45 imac demo[4352]: LOG SocketIOClient: Handling event: connect with data: (
    )
Jun 30 18:19:45 imac demo[4352]: LOG SocketEngine: Got message: 3
Jun 30 18:19:47 --- last message repeated 8 times ---
Jun 30 18:19:47 imac demo[4352]: LOG SocketEngine: Writing ws:  has data: 0
Jun 30 18:19:47 imac demo[4352]: LOG SocketEngine: Sending ws:  as type: 2
Jun 30 18:19:47 imac demo[4352]: LOG SocketEngine: Got message: 3
Jun 30 18:19:48 imac demo[4352]: LOG SocketIOClient: Client is being released
Jun 30 18:19:48 imac demo[4352]: LOG SocketEngine: Engine is being closed.
Jun 30 18:19:48 imac demo[4352]: LOG SocketEngine: Sending ws:  as type: 1
Jun 30 18:19:48 imac demo[4352]: LOG SocketEngine: Engine is being released

**Comment by sowrabhbs** [comment]
Found a solution for this issue.
In socket.ios.js file change the lines from
this.ios = SocketIOClient.alloc();
this.ios.initWithSocketURLOptions(NSURL.URLWithString(uri), options);
to
this.ios = SocketIOClient.alloc().initWithSocketURLOptions(NSURL.URLWithString(uri), options);

This will solve the problem.

**Comment by naderio** [comment]
makes sense. thanks @sowrabhbs 
patched in https://github.com/naderio/nativescript-socket.io/commit/33a2fb490dcdbeb6dde49fadf4a9662cdc611c11

**Comment by jonathan-casarrubias** [comment]
Awesome
