### ISSUE TITLE
iOS version not working.

### ISSUE THREAD

**Issue by eleddie** [naderio/nativescript-socket.io#11]
I managed to make it work on android, and it's working pretty well. But iOS version just wont connect when I call the `socket.on('connect', data => {...} );`. 

Any help on this would be appreciated. 
Thanks

**Comment by naderio** [comment]
@eleddie are you working with demo app?
in that case, did you update the IP address at https://github.com/naderio/nativescript-socket.io/blob/master/demo/app/connection.ts#L5

**Comment by eleddie** [comment]
No, I'm working on my own app. 
The domain has SSL.

Why would it work only on android?

**Comment by naderio** [comment]
well, unlike Android for which I have an app in production with secure domain, I didn't check for secure domains on iOS.
I should check this later...
do you have `secure: true` in `SocketOptions`?

**Comment by naderio** [comment]
@eleddie fixed in v0.4.1
issue due to bad URI parsing
