### ISSUE TITLE
Use with TNS NG2 - io is not defined

### ISSUE THREAD

**Issue by demym** [naderio/nativescript-socket.io#12]
Hi, 

i am trying to use this plugin with an NG2 Nativescript app. I used it successfully into another app written in vanilla JS nativescript, but i am not able to use it on NG2; 

I've put this into my code

<pre>
import * as SocketIO from 'nativescript-socket.io';
</pre>

But whenever i try to use the SocketIO var, the app crashes saying that io is not defined.

Any idea ? Thanks very much in advance

**Comment by naderio** [comment]
@demym I suppose this is on Android specifically, if this is the case, it would be related to `io.socket.*` Java class. `tns run android` would probably fix the issue, otherwise delete the `platforms` folder and rerun.

**Comment by demym** [comment]
Thanks, deleting the platforms folder did the trick
