### ISSUE TITLE
Error compiling on iOS

### ISSUE THREAD

**Issue by demym** [naderio/nativescript-socket.io#13]
Hi, 

i have and TNS android project with this plugin that runs perfectly now.

When i try to do TNS EMULATE IOS i have the following error:

<pre>
[!] Unable to satisfy the following requirements:

- `Socket.IO-Client-Swift (~> 8.1.1)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Socket.IO-Client-Swift (~>
8.1.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
Processing node_modules failed. Error: Command pod failed with exit code 1
</pre>

i don't know what this means.... do you have some idea ? Thanks in advance

**Comment by naderio** [comment]
please run `pod repo update`
