### ISSUE TITLE
Ack on emit

### ISSUE THREAD

**Issue by herpiko** [naderio/nativescript-socket.io#14]
Instead of default `function(){}`. is the `ack` in `function ack() {}` mandatory?

In the examples, there is arguments in ack scope. Where this argument come from?

**Comment by naderio** [comment]
1. nope, it's a now-obsolete best practice of naming a function defined as expression (for debugging purpose)
2. when the emitter sends something using `emitter.emit(event, payload, ack)`, the receiver gets `(payload, ack)` as arguments in `event` listener. If the receiver executes `ack`, it transmits its arguments back to the emitter.

**Comment by herpiko** [comment]
Thank you @naderio
