### ISSUE TITLE
One connection through multiple pages

### ISSUE THREAD

**Issue by bachras** [naderio/nativescript-socket.io#21]
Hi,

Thank you for nice plugin. I followed demo and tried to implement one connection through multiple pages but every time I require socket instance it connect as a new socket. How to solve this issue? Any help would be highly appreciated. Thanks

**Comment by naderio** [comment]
hi @bachras, the demo should work on multiple pages as is.

you need to have a dedicated module to manage socket.io connection (just like https://github.com/naderio/nativescript-socket.io/blob/master/demo/app/connection.ts) and import that module whenever you need it (`import socket from "./path/to/connection"` in TypeScript or `const socket = require('./path/to/connection').socket;` in pure JS).
