### ISSUE TITLE
Connection to server is disconnected when ios app switch to background

### ISSUE THREAD

**Issue by SandipFichadiya** [naderio/nativescript-socket.io#22]
Hello,
We are developing a chat application, which requires socket IO to work in background.
Whenever the app is in background and any message is received, notification must be fired to notify user of incoming message. 
But, connection to server is lost in background mode.
We checked server logs too,which shows "Disconnected" event fired. 

Does anyone has any idea of how to keep connection alive while app is in background ?

**Comment by naderio** [comment]
@SandipFichadiya please let me know:

1. what platform is touched by this issue?
2. is your socket.io instance initiated withing a page?
3. are you sure that the app is alive? 

Anyhow, I have this module used in 2 apps with different natures (driver and passenger) on Android and iOS.
Yes the OS, especially Android, kicks in if the app is kept in background and unused for a while (I measured 20 minutes on Android for one of the mentioned apps), other than that I don't have the interruption issue.

You could the following
- separate socket.io connection from page code (see the demo and #21)
- add `android:persistent="true"` tag to `<application />` in `AndroidManifest.xml`
- use https://github.com/EddyVerbruggen/nativescript-insomnia or a custom keep-alive routine

**Comment by bachras** [comment]
@naderio @SandipFichadiya have you solved this issue? I am having exactly same problem, everything works fine on android, but on iOS  once app goes in background socket stops listening for events. Any suggestion is highly appreciated. 

p.s. I have socket connection in separate page as suggested.
Thanks
