### ISSUE TITLE
Won't connect on Android but does on IOS

### ISSUE THREAD

**Issue by vincentduprez** [naderio/nativescript-socket.io#24]
I've developed my app for ios and trying to port it to Android but nativescript-socket.io won't connect, I narrowed the problem down to a simple hello world from the templates with only the nativescript-socket.io plugin. It works with IOS but not with Android. I get silent errors

running this bit of code :

```
export class AppComponent 
{
    socket;
    constructor()
    {
            console.log('constructor!');    
            this.socket = SocketIO.connect('https://eaglecar.org');
            this.socket.on('connect', ()=>
            {
                console.log('Connect!');
            });

            this.socket.on('error', (error) => 
            {
                console.log('Error!');
                console.log(error);
            });      
    }
}
```
For information, this connects to a server with a let's encrypt ssl certificate.

**IOS console output**

```
CONSOLE LOG file:///app/app.component.js:8:20: constructor!
CONSOLE LOG file:///app/tns_modules/@angular/core/./bundles/core.umd.js:3053:20: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
CONSOLE LOG file:///app/tns_modules/nativescript-socket.io/common.js:41:22: nativescript-socket.io on connect []
CONSOLE LOG file:///app/app.component.js:11:24: Connect!

```

**But with Android**

it silently fails given neither Connect! nor Error!

```
JS: constructor!
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
```
At first I was thinking about a timing error, so I tried to attach the connect to a UI callback, the function gets called but with no errors.

Can't find anything interresting with adb logcat but this, seems normal :

```
08-04 15:10:24.377 11162 11162 V JS      : constructor!
08-04 15:10:24.386 11162 11193 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-04 15:10:24.389 11162 11195 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-04 15:10:24.389 11162 11195 I System.out: (HTTPLog)-Static: isSBSettingEnabled false

```
Just tried to change the connecting domain to something that does not exist and still no error in the console...

**Additional tests :**

2 tests I made :

I successfully loaded an image over https in the same app on the same server with the same certificate
I successfully connected to a non secure socket.io server on another port (3000) on Android.

**Server side**

```
var fs = require('fs');
var options = {
    key:    fs.readFileSync('../ssl/keys/[this_is_a_valid_key].key'),
    cert:   fs.readFileSync('../ssl/certs/[this_is_a_valid_cert].crt')
};


var server = require('https').createServer(options);
server.listen(443,'eaglecar.org');
var io = require('socket.io').listen(server);


io.on('connection', function(socket){
  console.log('connected!!');
});
```

**Comment by vincentduprez** [comment]
Ok I figured it out, Let's encrypt is **NOT** supported, just switched to another provider and everything is smooth now.

**Comment by naderio** [comment]
@vincentduprez great! you find the issue here, still I have Let's Encrypt working ok with this plugin on production with both iOS and Android, I'll keep this open to investigate the issue...

**Comment by ngunhaSO** [comment]
I am facing the same issue. My server is https, it is connected fine on iOS. However with Android, the initial connection is ok, then after a few seconds, it is socket on error with no detail info and finally socket disconnect with 'transport error'. 
@vincentduprez what was your work around for the Android?
