### ISSUE TITLE
QUESTION New version on sever?

### ISSUE THREAD

**Issue by devyaz** [naderio/nativescript-socket.io#25]
can i use socketio version 2.4.0 on the server with this one?

**Comment by naderio** [comment]
@devyaz the latest version of Socket.IO is 2.0.3. There is no 2.4.0.

**Comment by devyaz** [comment]
my bad just a typo, but i tried and it works thanks @naderio  i have 2.0.3 on the server!!, i don'i know how to build plugins, so ill use this opportunity to ask, there's a background app plugin i used in a cordova project, was wondering if you could port it to so socket.io can receive in the bacground {N} [background mode](https://github.com/devyaz/cordova-plugin-background-mode) , please take a look

**Comment by naderio** [comment]
I think it is not possible to use socket.io in background
