### ISSUE TITLE
Building failed, can't run "npm run ios" in a nativescript folder under seed context (exit code 65)

### ISSUE THREAD

**Issue by aforamenta** [naderio/nativescript-socket.io#31]
**The seed I'm using, which is the maestro native angular2 seed, works perfectly.** However I think the plugin is broken, for some reason.

1 - I added the plugin to the package.json

2 - I updated and installed the plugins in package.json

3 - I ran "npm run ios" and compilation began. **Before the plugin everything was working so far**.

Here are the relevant logs after `npm run ios`:

> (...)
> Using GoogleMaps (2.5.0)
> Installing Socket.IO-Client-Swift (12.1.2)
> Installing Starscream (2.1.1)
> Generating Pods project
> Integrating client project
> Pod installation complete! There are 2 dependencies from the Podfile and 3 total pods installed.
> [WARNING]: [!] Automatically assigning platform ios with version 8.0 on target nativescript because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Errors thrown by **CompileSwift**:

> /Users/air/Desktop/Repos/B13/nativescript/platforms/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Engine/SocketEngine.swift:228:43: error: value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?
>         if let data = Data(base64Encoded: noPrefix, options: .ignoreUnknownCharacters) {

> /Users/air/Desktop/Repos/B13/nativescript/platforms/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Engine/SocketEngine.swift:521:34: error: value of type 'String' has no member 'dropFirst'
>             handleMessage(String(message.dropFirst()))
>                                  ^~~~~~~ ~~~~~~~~~
> /Users/air/Desktop/Repos/B13/nativescript/platforms/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Engine/SocketEngine.swift:527:41: error: value of type 'String' has no member 'dropFirst'
>             handleOpen(openData: String(message.dropFirst()))
                
> /Users/air/Desktop/Repos/B13/nativescript/platforms/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Engine/SocketEnginePollable.swift:187:19: error: 'count' is unavailable: there is no universally good answer, see the documentation comment for discussion
>         guard str.count != 1 else { return }
>                   ^~~~~
> Swift.String:231:16: note: 'count' has been explicitly marked unavailable here
>     public var count: Int { get }

Finally:

> **The following build commands failed:**
> CompileSwift normal x86_64 /Users/air/Desktop/Repos/B13/nativescript/platforms/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Engine/SocketEngine.swift
> 	CompileSwift normal x86_64 /Users/air/Desktop/Repos/B13/nativescript/platforms/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Engine/SocketEnginePollable.swift
> 	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
> (3 failures)
> Multiple errors were thrown:
> **Command xcodebuild failed with exit code 65**

Any idea on what might be wrong here? Is the plugin known to be broken?
Thank you

**Comment by aforamenta** [comment]
@naderio Please check this out :) thank you

**Comment by naderio** [comment]
@rcc26 latest version of this plugin uses [socket.io-client-swift](https://github.com/socketio/socket.io-client-swift/releases/) v12.0

please make sure that your codebase [enforces usage of Swift 3](https://github.com/naderio/nativescript-socket.io/blob/master/demo/app-base/platforms/ios/Podfile) and/or use an earlier versions of this plugin:

- 0.7.1 (uses socket.io-client-swift v11.0)
- 0.6.0 (uses socket.io-client-swift v10.0)
- 0.5.0 (uses socket.io-client-swift v8.1, works for sure, apps in production on Android and iOS)

Frankly I didn't actually test on iOS on versions after 0.5.0 and - based on socket.io-client-swift changelog - I assumed there would be no breaking upgrade.

Anyhow, please do as suggested and let me know.

**Comment by aforamenta** [comment]
Hello @naderio , thanks for replying!

I tried to use the version 0.5.0 but unfortunately **the app still does not run** with the same error and logs...

What exactly should I try next to check why this is not working?
Thank you for your help! :)

**Comment by naderio** [comment]
Apparently this is not a plugin version issue as much as a Swift version issue.

You need to [enforces usage of Swift 3](https://github.com/naderio/nativescript-socket.io/blob/master/demo/app-base/platforms/ios/Podfile) by adding a local plugin forcing all plugins to use the same version of Swift ; otherwise you risk this issue reappearing with other plugins as well

**Comment by naderio** [comment]
and when you change a version make sure to delete platforms folder

**Comment by aforamenta** [comment]
"and when you change a version make sure to delete platforms folder" - I had forgotten about this but I erased it now. **It is running with version 0.5.0**. 

1 - How exactly can I enforce usage of Swift 3 in this angular environment?

2 - How bad would it be for me to be relying on version 0.5.0 for production purposes?

**Comment by aforamenta** [comment]
@naderio (forgot to tag name, sorry :) )

**Comment by naderio** [comment]
If it works with version 0.5.0 then your setup is using Swift 3 already (some plugin you're using must be enforcing this for you)

Would you kindly test versions 0.7.1 and 0.6.0 for me. I'm going to rollback to earlier version of socket.io-client-swift but I don't know which one (I suspect v12 is using Swift 4 therefore I would rollback to v11)

Otherwise, v0.5.0 is reliable but better stay on latest, I'll release a fix for this.

**Comment by aforamenta** [comment]
Yeah yeah, I'll test both now. Will report back, thanks for your help @naderio :)

**Comment by aforamenta** [comment]
@naderio **both 0.6.0 and 0.7.1 seem to be working under an iOS context** :) I'll stick to 0.7.1 for now

**Comment by naderio** [comment]
Thank you @rcc26 
Published [v0.9.0](https://github.com/naderio/nativescript-socket.io/releases/tag/v0.9.0) rolling back to socket.io-client-swift v11.0
