### ISSUE TITLE
Socket instance in multiple pages

### ISSUE THREAD

**Issue by devyaz** [naderio/nativescript-socket.io#32]
hi @naderio  a question, how can i use a socket instance in multiple pages, like socket is connected on login page then use that socket instance in a chat page which is actually a third page , i used the 
 {N} background sample App code in my app and i can get messages even after my App is killed! but to do it, the background service has to do a new connection, {N} apps takes up to 10 min running even after closing/exiting the app!!  so the background service fails to connect until Android kills App! a workaround is i disconnect the socket on App close/exit which works fine until i click the notification which starts the App but the app's chat has no connection to the current  socket connection made in the background service, in short i want to use a single socket instance in main thread (app) and background

**Comment by naderio** [comment]
please refer to `socketio.ts` (no authentication) and `socketio-managed.ts` (authentication or conditional connection) under `demo/app`

**Comment by devyaz** [comment]
thank you for the prompt response @naderio

**Comment by naderio** [comment]
otherwise I this it is not possible to share the same JS object reference between UI thread and background service

**Comment by devyaz** [comment]
But now I tried putting the socket connection logic in a separate file and refer(require) it in my home page and background, it works but can’t clone the JS Object, ill try to use  socketio-managed.ts
