### ISSUE TITLE
Does this plugin support transport mode websocket?

### ISSUE THREAD

**Issue by shiv19** [naderio/nativescript-socket.io#34]
According to an article I was reading,
socket.io tries to upgrade to websocket connection, whenever it is available.
I was not able to see any upgrade request going form this plugin..

Does this plugin support websocket transport mode for socket.io ?

**Comment by naderio** [comment]
@shiv19  to my understanding, mobile native implementations do not behave like web implementation, instead they try to connect directly with WebSocket, otherwise fall back to HTTP
this plugin doesn't do anything special regarding this matter.

**Comment by shiv19** [comment]
Thanks @naderio 
Currently I'm using transport mode set to web sockets. and it works fine.
