### ISSUE TITLE
reconnection

### ISSUE THREAD

**Issue by abolinhas** [naderio/nativescript-socket.io#36]
Hi,
Is the any way to stop automatically reconnection?
I already try {'reconnection': false} and {'reconnect': false} inside option but none works
Best regards

**Comment by naderio** [comment]
Hi @abolinhas,
try the following
```javascript
const options = {
  android:  {
    reconnection: false,
  }
};

const socketio = SocketIO.connect('http://somewhere/namespace', options);
```
