### ISSUE TITLE
Cannot connect after manual disconnect

### ISSUE THREAD

**Issue by bachras** [naderio/nativescript-socket.io#37]
First, I want to thank for brilliant plugin, it works as expected. I just have one issue. when app is loaded user is connected to socket.io server and everything works fine, but once user logs out from the app I manually disconnect the socket(so user doesn't get notifications and so on) and redirect user to login page. If user decides to login without refreshing the app, on login user is not connected to socket.io server. Everything works fine once app is closed and opened again. Any help or advised would be highly appreciated. Thanks

**Comment by naderio** [comment]
@bachras which version of `nativescript-socket.io` are you using?
