### ISSUE TITLE
Unable to use it on iOS

### ISSUE THREAD

**Issue by shiv19** [naderio/nativescript-socket.io#39]
I get this error message in the console
```
file:///app/tns_modules/nativescript-socket.io/socketio.js:53:67: JS ERROR TypeError:
 SocketIOClient.alloc().initWithSocketURLConfig is not a function. (In 
'SocketIOClient.alloc().initWithSocketURLConfig(NSURL.URLWithString(uri), _options)', 
'SocketIOClient.alloc().initWithSocketURLConfig' is undefined)
```

**Comment by shiv19** [comment]
This happens when you have a plugin that depends on Swift version 4.0
in your project.

I had to remove nativescript-cfalert-dialog

**Comment by shiv19** [comment]
also if you set 
transport: "websocket"

in the query object, it won't connect on iOS

**Comment by naderio** [comment]
@shiv19 Swift 4 is not supported yet since it is not a simple upgrade (Socket.IO Swift implementation have changed its API)

**Comment by shiv19** [comment]
Thank you for the explanation :)

**Comment by phenric** [comment]
I also have the same issue. But since a year has passed, maybe Swift 4 is supported now ? :)

**Comment by naderio** [comment]
Swift 4 is supported in latest release

**Comment by phenric** [comment]
Thx for your reply !
But I still have the issue with nativescript-socket.io :

> (CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: SocketIOClient.alloc().initWithSocketURLConfig is not a function. (In 'SocketIOClient.alloc().initWithSocketURLConfig(NSURL.URLWithString(uri), _options)', 'SocketIOClient.alloc().initWithSocketURLConfig' is undefined)

Could you help me ? :)

**Comment by phenric** [comment]
I found the solution.
Sometimes, easy paths are the best. I've used the command `tns clean platform ios` and everything is fine now.
