### ISSUE TITLE
MalformedURLException when attempting to connect using websockets

### ISSUE THREAD

**Issue by geoff-riverkids** [naderio/nativescript-socket.io#41]
when building an android app, calling to connect to a secure websocket URI fails:

var SocketIO = require('nativescript-socket.io').SocketIO;
..
var socket = new SocketIO('wss://api.serverbeta.com:8118', { transport: websockets, reconnection: true, secure:true });
this.socket = socket;
..
socket.connect();

**Comment by naderio** [comment]
@geoff-riverkids the passed URI should have `http://` or `https://` scheme, not `wss://`

**Comment by geoff-riverkids** [comment]
this isn't a solution lol

**Comment by naderio** [comment]
@geoff-riverkids as far as I know socket.io doesn't even support creating a connection directly with `ws` and `wss` schemes
socket.io client require a socket.io backend, usually running under `/socket.io/` (in your case https://api.serverbeta.com:8118/socket.io/), and should return something like `{"code":0,"message":"Transport unknown"}` upon direct usage in browser.

**Comment by geoff-riverkids** [comment]
ahhhh I see.  socket.io 2.x javascript version has this direct scheme support but:

https://github.com/socketio/socket.io-client-java

 is the problem.

We are trying to move from Cordova to NativeScript and dated plugins are what we are finding.
