### ISSUE TITLE
Is there a disconnect event?

### ISSUE THREAD

**Issue by FranciZ** [naderio/nativescript-socket.io#43]
Hi,

I have the following setup which connects to my API. The disconnect event never fires if I bring the API down. Is there some other way to check for this other than having an interval which checks `socketio.connected`? Thanks!

```typescript
    const socketio = SocketIO.connect(this.API_HOST);

    socketio.on('connect', () => {
      console.log('SocketIO - CONNECTED');
      this.rootStore.socketStatus = SocketStatus.ONLINE;
    });

    socketio.on('disconnect', () => {
      console.log('SocketIO - DISCONNECTED');
      this.rootStore.socketStatus = SocketStatus.OFFLINE;
    });
```

**Comment by naderio** [comment]
@FranciZ disconnect `socketio.on('disconnect', () => { /* ... */ })` should be operationnal
if not, please provide envirenment information and library version
