### ISSUE TITLE
need upgrade to {N} V4 ?

### ISSUE THREAD

**Issue by OPADA-Eng** [naderio/nativescript-socket.io#46]
Hi, I'm trying to use this plugin in my app that use {N} v4, but it does not work with me.
When I'm trying to connect to the server I got this error:

> CONSOLE LOG file:///app/tns_modules/nativescript-socket.io/socketio.common.js:55:22: nativescript-socket.io on error ["Transport unknown"]

I don't know the reason but I suspect the reason from the version.
Any help please ?

**Comment by naderio** [comment]
Hi @OPADA-Eng,
I have this plugin functional with NativeScript v4 on production with latest Socket.IO on server.
Is the provided log part of crash error? in that case please provide stack-trace and server version of Socket.IO.

**Comment by OPADA-Eng** [comment]
Hi @naderio  Thank you for support.
I have reconfigured the server and discovered that the problem was from the server. 
now it's working fine!
