### ISSUE TITLE
IOS `init` is depricated 

### ISSUE THREAD

**Issue by kefahB** [naderio/nativescript-socket.io#48]
Hello,

There is sum deprecated on IOS.

Do you know for how many time it will be suproted for the new IOS ?

`
[18-07-29 20:48:50.004] (CLI) 'init' is deprecated
[18-07-29 20:48:50.004] (CLI)             return String(substring)!
[18-07-29 20:48:50.004] (CLI)                    ^
[18-07-29 20:48:50.004] (CLI) [xcode-build] /tmp/builds/_/b2850e784066d55f858e7801db7100595729e766/4.1.2/DIGIPAYMERCHANT/platforms/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Util/SocketStringReader.swift:67:16
`

Thank you.

**Comment by packytagliaferro** [comment]
Yes I have a lot of warnings to related to Swift 4 

```
Warning: Swift 3 mode has been deprecated and will be removed in a later version of Xcode. Please migrate "Socket.IO-Client-Swift" to Swift 4.2 using "Convert > To Current Swift Syntax…" in the Edit menu. (in target 'Socket.IO-Client-Swift')
warning: Swift 3 mode has been deprecated and will be removed in a later version of Xcode. Please migrate "Socket.IO-Client-Swift" to Swift 4.2 using "Convert > To Current Swift Syntax…" in the Edit menu. (in target 'Socket.IO-Client-Swift')
```

**Comment by b02505048** [comment]
Same problem here, any solution?

**Comment by kefahB** [comment]
Hi,

You have the old version of nativescript-socketio, update to the latest and the error will normally disappear.

**Comment by b02505048** [comment]
Hi @kefahB, thanks for replying

My version is `"nativescript-socket.io": "^0.9.0"`
I thought it's already the newest version?

**Comment by kefahB** [comment]
Oh I am sorry i confused with other plugin for web socket .. take a look [here](https://github.com/triniwiz/nativescript-socketio/issues/62) if you want

**Comment by b02505048** [comment]
Hi @kefahB, I tried 
```
tns plugin remove nativescript-socket.io
tns plugin add nativescript-socket.io
```

and what I get is still `v0.9.0` and `tns plugin add nativescript-socket.io@3.0.2` returns `No matching version found`.

Are you sure the actual version of `nativescript-socket.io` you're running is `3.0.2`? Thank you

**Comment by kefahB** [comment]
@b02505048 I am really sorry i received tow notifications in the same day from `nativescript-socket.io` and `nativescript-socketio` and i am confused about this issue and another one ! 

I did not use this plugin anymore .. i use `nativescript-socketio`

**Comment by b02505048** [comment]
@kefahB, same here. Plus, `nativescript-socketio` is now verified plugin, Cheers!
