### ISSUE TITLE
IO is not defined

### ISSUE THREAD

**Issue by moshmage** [naderio/nativescript-socket.io#5]
So.. All I did was

``` sh
tns plugin add nativescript-socket.io
```

To install the plugin.

When I 

```
const SocketIO = require('nativescript-socket.io');
```

It simply tells me [`io is not defined`](http://imgur.com/a/G1hrD) (last line of log)

It appears that the [declaration of io var](https://github.com/naderio/nativescript-socket.io/blob/master/socket.android.ts#L3) has no real value on the ES2015 equivalent.

**Comment by PatrickVienne** [comment]
Hi,

I have the same issue.
`io is not defined`
after installing the plugin with:
tns plugin add nativescript-socket.io

how did you solve it?

Thanks,
Patrick

**Comment by moshmage** [comment]
@PatrickVienne I think I fixed this by rebuilding the application *after* I added the new plugin. Hell, I made it a rule that whenever I add a plugin I uninstall the app from the vm-mobile and re-install the new build with the new plugins.

**Comment by accordionpeas** [comment]
Hi,

I'm getting the same error. Why was this issue closed?

Thanks,

Mike

**Comment by PatrickVienne** [comment]
Completely deleting the app from the device first and reinstalling was the solution in my case as well.
Thanks a lot for the quick response!!

**Comment by thiagomotta** [comment]
Hello,
I have the same problem.
I already uninstall app my device, but a keep getting: "IO is not defined"

"nativescript-socket.io": "^0.9.0"

I need help, please
Thanks :D
