### ISSUE TITLE
iOS Swift 4.0 Build Failed

### ISSUE THREAD

**Issue by b02505048** [naderio/nativescript-socket.io#50]
Am using **XCode 10.1** with **Swift 4.0**
and required to use `nativescript-algolia` which must work under Swift 4.0

```
pod 'AlgoliaSearch-Client-Swift', '~> 5.0'

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
end
```

May I ask is it currently supporting Swift 4.0 or above ? Thank you!

**Comment by naderio** [comment]
@b02505048 Swift 4.0 requires upgrading the native part which have some breaking changes
there is no plan for upgrading for now
