### ISSUE TITLE
Use websocket only on android

### ISSUE THREAD

**Issue by Upd4ting** [naderio/nativescript-socket.io#52]
Hello, i'm using this code client side to connect on my clusterised socket io server

`socketio = SocketIO.connect('http://IP/app', {
			query: 'token=' + token,
			forceNew: true,
			secure: false,
			android: {
				transports: ['websocket', 'polling'],
			},
			ios: {
				transports: ['websocket', 'polling'],
				forceWebsockets: true,
			}
		});`
But even with that my server receive connection trying to use polling and trigger a transport error because polling with clustering isn't compatible. How can I ensure that my client won't try polling at all?

**Comment by naderio** [comment]
@Upd4ting do no pass `'polling'` to `transports` options

**Comment by Upd4ting** [comment]
That's not a solution I already tried and first request always try doing polling but as my socket io is clusterised, the polling handshake won't work and trigger a transport error

**Comment by naderio** [comment]
@Upd4ting the following works for a similar use case as yours in production:
```
const socketio = SocketIO.connect(`${PARAM.ENDPOINT}/`, {
    android: {
      forceWebsockets: true,
    },
    ios: {
      forceWebsockets: true,
    },
    query: {
      token: STATE.token,
    },
});
```

**Comment by Upd4ting** [comment]
`let token = randomString(15);
        socketio = SocketIO.connect('http://192.168.0.7:1337/app', {
			query: {
				token: token
			},
			android: {
				forceWebsockets: true,
			},
			ios: {
				forceWebsockets: true,
			}
		});`

Tried some test in local and that's not working. Server side logs:
engine handling "POST" http request "/socket.io/?EIO=3&token=RJQTf8lLJA14xSZ&sid=BzdR8kN_NaAEcOjrAABX&transport=polling"

As you see that's still trying polling transport and not websocket :/

**Comment by standevo** [comment]
Why this post was closed without any working solution?

I have the same problem. Even I force the client to use only websocket, on clustered server I get always: 

`engine handling "GET" http request "/socket.io/?EIO=3&transport=polling&token=x"`
`engine setting new request for existing client`
`socket.io:client client close with reason transport error`
`socket.io:socket closing socket - reason transport error`

**Comment by naderio** [comment]
reopening, @Upd4ting @csi-stasik let's establish current state:

I've the following setup fully functional in prod: 
- multiple instances
- using socket.io-redis (https://socket.io/docs/using-multiple-nodes/#Passing-events-between-nodes)
- nginx load balancing (https://socket.io/docs/using-multiple-nodes/#NginX-configuration)
- client connects with snippet provided above

are you using a similar setup or not? and what versions are using of `socket.io` in the backend and `nativescript-socket.io`? android or ios or both?

**Comment by Upd4ting** [comment]
Hello @naderio,

Thanks for trying to help!
You don't have the problem because you're using nginx load balancing that use ip hash system. IP hash ensure that a client will always be redirected to the same cluster and so polling handshake will success.

I'm using pm2 clustering with built-in load balancing and that's not using ip-hash. 

That's why i'm trying to tell socket io to not event try to connect with polling and use websocket directly. But it seems that socket io keeps trying polling as first transport solution :/

**Comment by standevo** [comment]
@naderio, Thanks for replay

I have only dev environment for the moment, I'm using:
- Multiple workers/instances with pm2-dev in cluster mode (with single instance it's working fine)
- using socket.io-redis (but I'm not arrive to using it because after connection its disconnect, I'm not send/receive any other messages yet)
- My client options:

```
const options: SocketIO.SocketOptions = {
      android: {
        transports: ["websocket"],
        // forceWebsockets: true -> I tried also with this.
      }
      query: {
        token: "my_token"
      }
    };

const io = SocketIO.connect(environment.socketUrl, options);

```

Result:

Its called the connection event but after I get

```
engine handling "GET" http request "/socket.io/?EIO=3&transport=polling&token=x"
engine setting new request for existing client
socket.io:client client close with reason transport error
socket.io:socket closing socket - reason transport error
```

**Comment by naderio** [comment]
@Upd4ting I had the same setup which didn't work so I've switched load balancing to nginx instead of pm2, that's why it works for me even with polling
my setup have socket io listen to separate port per instance (making use of pm2' instance number/id `process.env.NODE_APP_INSTANCE`) and nginx load balancing on those ports as in the provided snippet
@csi-stasik @Upd4ting for there is no `forceWebsockets` for android => `transports: ['websocket']`
I'm looking into this ...

**Comment by standevo** [comment]
@naderio Thank you, now the reason is clear.

**Comment by Upd4ting** [comment]
@naderio I see, is it possible to have this option on android you think ?

**Comment by naderio** [comment]
@Upd4ting i'm inspecting the native java code, will see

**Comment by Upd4ting** [comment]
Thanks!

**Comment by naderio** [comment]
@Upd4ting @csi-stasik  i've managed to make it work but it is not a clean code, maybe I add an option to do this, anyhow following works on websocket:

```javascript
function connect() {
  const transports = Array.create(java.lang.String, 1);
  transports[0] = 'websocket';

  socket.io = SocketIO.connect(`PARAM.ENDPOINT, {
    android: {
      transports,
    },
    ios: {
      forceWebsockets: true,
    },
    query: {
      token: STATE.token,
    },
  });
};
```

The issue was array conversion from JavaScript to Java

**Comment by Upd4ting** [comment]
Sweet!

Will this line const transports = Array.create(java.lang.String, 1); fail on IOS ?

**Comment by naderio** [comment]
@Upd4ting  you're right

```javascript
const platformModule = require("tns-core-modules/platform");

function connect() {
  let transports = null;

  if (platformModule.isAndroid) {
    transports = Array.create(java.lang.String, 1);
    transports[0] = 'websocket';
  }

  socket.io = SocketIO.connect(PARAM.ENDPOINT,  {
    android: {
      transports,
    },
    ios: {
      forceWebsockets: true,
    },
    query: {
      token: STATE.token,
    },
  });
};
```

**Comment by standevo** [comment]
@Upd4ting, Great workaround, now it forcing the websockets only (in future version it will be nice to include also this fix). Thanks anyway.

But after your previous replay I like more the idea of nginx load balancing instead of pm2 (buildin load balancing) and polling sacrifice in clustered server.

**Comment by Upd4ting** [comment]
@naderio Great! Thanks :)

**Comment by Upd4ting** [comment]
@naderio Since i'm using this I got a crash on Huawei p20

> com.tns.NativeScriptException: Calling js method instantiateItem failed
Error: java.lang.NoSuchMethodError: no non-static method "Landroid/support/v4/app/FragmentManagerImpl;.findFragmentByTag(Ljava/lang/String;Lio/socket/client/IO$Options;)Lio/socket/client/Socket;"

Do you know what that could be ?

**Comment by naderio** [comment]
@Upd4ting no idea

**Comment by standevo** [comment]
@Upd4ting, On other devices work? Can you share the code of socket initialization, I have no problems on Android simulator and LG G6 (I adapted the @Upd4ting's solution for typescript)

**Comment by Upd4ting** [comment]
I used @naderio one, but that's doing that error only on some device and not every time I think
