### ISSUE TITLE
Plugin is not compatible with xcode 10.2  

### ISSUE THREAD

**Issue by OPADA-Eng** [naderio/nativescript-socket.io#53]
Hi, 
Thanks for your great plugin.
I noticed after I update my xcode today that the build is not complete and get these errors in cli: 

> Xcode build...
error: SWIFT_VERSION '3.1' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'Socket.IO-Client-Swift')
error: SWIFT_VERSION '3.1' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'Socket.IO-Client-Swift')
note: Using new build systemnote: Planning buildnote: Constructing build description
** BUILD FAILED **

any help to build the app ?

**Comment by hhanckes** [comment]
I am running with the same issue. Please help. Thanks!

**Comment by LeCoupa** [comment]
Same for me :) Did you found a solution? I'm struggling to fix this since a few hours now.

**Comment by OPADA-Eng** [comment]
Hi all, the solution is in my pull request.
Regards

**Comment by naderio** [comment]
Issue fixed in version [0.10.0](https://github.com/naderio/nativescript-socket.io/releases/tag/v0.10.0)

@OPADA-Eng thank you for the PR
