### ISSUE TITLE
Not working on android :(

### ISSUE THREAD

**Issue by jannomeister** [naderio/nativescript-socket.io#58]

**Comment by jannomeister** [comment]
@naderio any update on this plugin? It is working on iOS but in android its not :( Also the demo's nativescript version is not the latest one.

**Comment by jannomeister** [comment]
I badly need it on my application :(

**Comment by jannomeister** [comment]
@naderio hello? :(

**Comment by naderio** [comment]
@jannomeister demo code is not updated but I have the latest version working with NativeScript 6 on a yet unreleased production app.
please provide and error message or stack trace.
you can also listen to error event and display that message.

**Comment by jannomeister** [comment]
@naderio there's no printed error when I tried it on android.

**Comment by naderio** [comment]
try to add loggers to following event:

```javascript
socketio.on('connect', function(){
  console.log('connect');
});

socketio.on('disconnect', function(){
  console.log('disconnect');
});

socketio.on('error', function(err){
  console.log('error', err);
});
```

**Comment by jannomeister** [comment]
@naderio yep, I tried that one. Still not logs occur

**Comment by naderio** [comment]
hi @jannomeister , I've this working with an app that I've upgraded a couple of days ago. all works fine.
please recheck your setup (code, network, server, ...) and maybe try to use this plugin with a freshly created app with confirmed functional server.

**Comment by jannomeister** [comment]
Hi @naderio,  I tested it with the latest version of nativescript and nativescript-angular, Also I use a simple express server. I include a sample project with the ns-app and the demo-server. You can test it. 

NS-App: `cd socketApp` and do `tns run ios/android`
Server: `cd demo-server` and do `node app`

It works on iOS and not on Android. Hope you have time to test this sample work I sent.

[socketSample.zip](https://github.com/naderio/nativescript-socket.io/files/3499709/socketSample.zip)

NOTE: on iOS it triggers the `connect` event as expected. But not on android

**Comment by jannomeister** [comment]
@naderio  did you test the sample app?

**Comment by jannomeister** [comment]
@naderio I used your demo-server and still not working on android.

**Comment by iurydias** [comment]
I'm struggling to make it works on Android, but not succeeded. That was the only lib, among few that exist, which have support, apparently.

**Comment by naderio** [comment]
@jannomeister @iiurydias I try to reproduce the issue but I'm unable to do so due to lack of information.
Again, I have the latest version working with NativeScript v6 (after upgrade) and prior versions with no issues.
What you can do is to provide you environment (versions of java, android sdk tools, node, npm, nativescript) and logs/stacktrace.

**Comment by jannomeister** [comment]
@naderio 
```
java: 1.8.0_202
android sdk: (build-tools) 28.0.3
node: v10.15.3
npm: v6.4.1
nativescript: 6.0.3
```

this is my environment version. Sad to say no logs produce when im connecting in android. This is the best I could do. Hoping also you try my sample project together with your demo-server with these environments.

**Comment by iurydias** [comment]
First of all, it works fine with nativescript-vue?

**Comment by naderio** [comment]
it seems that it is not working due to `connect` not being fired

**Comment by naderio** [comment]
@jannomeister  @iiurydias  finally the issue seems to be caused by Android 8 network security configuration, and not by this plugin itself. 

make sure that your `AndroidManifest.xml` contains the following

```xml
<application ...android:networkSecurityConfig="@xml/network_security_config" ...>
```
and you have `app/App_Resources/Android/src/main/res/xml/network_security_config.xml` file containing the following

```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
  <domain-config cleartextTrafficPermitted="true">
    <domain includeSubdomains="true">192.168.1.111</domain>
  </domain-config>
</network-security-config>
```

where `192.168.1.111` is your domain or IP address.

**Comment by naderio** [comment]
also updated the demo to nativescript v6

**Comment by phaeton2040** [comment]
Encountered the same issue:

`SocketIO.connect('http://10.0.2.2:8080/client')`

`socket.on('connect_error', (err) => {
  console.log('on connect error: ', err)
})`

gives me `on connect error: null` in console

Tried adding network config to AndoidManifest.xml, still no luck

**Comment by phaeton2040** [comment]
I also deployed my socket.io server to a server with external IP. Still cannot connect.

**Comment by naderio** [comment]
@phaeton2040 for sure it wont connect without Android network configuration with correct IP address or domain.
it should work fine for local network, no need for deployment.
other than that I have no idea

**Comment by phaeton2040** [comment]
Still no luck with connecting from android. Any advice? What else should I check?

**Comment by phaeton2040** [comment]
I was also unable to connect with api version 27 which has clear text traffic support
