### ISSUE TITLE
tns plugin add nativescript-socket.io is not working with 0.11.0

### ISSUE THREAD

**Issue by rosen-vladimirov** [naderio/nativescript-socket.io#59]
When executing the `tns plugin add nativescript-socket.io`, the command fails with error `Invalid version ^2.0.0`. The problem is that NativeScript CLI tries to validate if the values in the nativescript key of the package.json of the plugin is lower than the current platform version. NativeScript CLI does not support semver versions in the nativescript key of the plugins. I.e. the changes in 0.11.0:
```
"nativescript": {
   "platforms": {
     "ios": "^2.0.0",
     "android": "^2.0.0"
   }
 }
```
Should be:
```
"nativescript": {
   "platforms": {
     "ios": "2.0.0",
     "android": "2.0.0"
   }
 }
```

Steps to reproduce:
```
1. tns create myApp --js
2. tns platform add android
3. tns plugin add nativescript-socket.io
```

**Comment by naderio** [comment]
@rosen-vladimirov thank you for the clarification. issue fixed in version 0.11.1.
