### ISSUE TITLE
Error Could not find module 'nativescript-socket.io'.

### ISSUE THREAD

**Issue by sowrabhbs** [naderio/nativescript-socket.io#6]
while launching of application.

**Comment by dxshindeo** [comment]
Having the same error. `import SocketIO = require("nativescript-socket.io");` 
However, this worked: `var SocketIO = require('nativescript-socket.io');`

But now I'm getting error _"io is not defined"_.
I presume I don't have those dependencies? How do I get them/install them?
`Android: Socket.IO-client Java v0.8.*
iOS: Socket.IO-Client-Swift v8.1.*`

I see that in `include.gradle` file you specify it as a dependency:
`dependencies {
    compile ('io.socket:socket.io-client:0.8.+') {
      exclude group: 'org.json', module: 'json'
    }
}
`
Upon further research (https://docs.nativescript.org/plugins/plugins#includegradle-specification):
`Any native dependencies should be available in jcenter or from the Android SDK installed on your machine.`

I doubt this library is locally on Android SDK, so probably we are getting it from here: https://bintray.com/bintray/jcenter/io.socket%3Asocket.io-client

In `socket.d.ts` file, I see 2 errors:
First - `public android: io.socket.client.Socket;` - here is where the io cannot be found.
Second - `import * as helpers from "./helpers";` - says _"Import or Export declaration is an ambient module declaration cannot reference module through relative module name"_

**Comment by naderio** [comment]
checking this issue...
native dependencies are added when plugin is installed.
otherwise I have this working on in a JavaScript-based app on both iOS and Android. I probabaly need to check with TypeScript.

**Comment by naderio** [comment]
reopened

**Comment by naderio** [comment]
please check v0.2.3 .. should be fine

**Comment by dxshindeo** [comment]
Thank you, it works now :)

**Comment by sowrabhbs** [comment]
its working,Thanks @naderio
