### ISSUE TITLE
Error in pod install

### ISSUE THREAD

**Issue by Serranom4** [naderio/nativescript-socket.io#8]
When I try to build my app with `$ tns build ios` I get this error: 
![screen shot 2016-11-22 at 12 40 57 pm](https://cloud.githubusercontent.com/assets/17414885/20537004/00b5a280-b0b1-11e6-8f15-6bb92b020835.png)

All I did was : 
`
 $ tns create test-app --ng
`
`
 $ tns plugin add nativescript-socket.io
`
`
 $ tns platform add ios
`
`
 $ tns build ios
`

I found that changing the Podfile to
` pod 'Socket.IO-Client-Swift', :git => 'https://github.com/socketio/socket.io-client-swift.git'`
instead of 
` pod 'Socket.IO-Client-Swift', '~> 8.1.1'`
fix the problem but I'm not sure if this is the best solution.

**Comment by naderio** [comment]
`8.1.1` is a valid Socket.IO-Client-Swift [tag/version](https://github.com/socketio/socket.io-client-swift/releases/tag/v8.1.1).
did you try `pod repo update`?

**Comment by Serranom4** [comment]
`pod repo update` fix the problem, thanks!
