### ISSUE TITLE
once function for feathers authentication

### ISSUE THREAD

**Issue by fuleshu** [naderio/nativescript-socket.io#9]
Hi,

I use this library together with `featherjs.`
The feathers authentication over sockets makes  use of the `once` function available in `socket.io-client`.
The code from there is quite simple, it replaces the handler with a wrapper, that when called executes the callback and removes itself from the event:
```javascript
Emitter.prototype.once = function(event, fn){
	  function on() {
	    this.off(event, on);
	    fn.apply(this, arguments);
	  }
	  on.fn = fn;
	  this.on(event, on);
	  return this;
	};
```
I tried to add this function in my code, but my javacript skills are not so well, so I ended up with this:
```javascript
        this.socket.once = (event, fn) => {
            let on = (args) => {
                this.socket.off(event);
                fn(args);
            }
            this.socket.on(event, on);
        };
```
This instead of just removing the one handler from the event removes every handler for the event. I didn't manage to get it work the other way. However, featherjs authentication works now for me.

I think it would be great to add `once` to this library, so feathersjs would work out of the box. I guess it should be easy to add for someone who knows this lib.

Cheers,
Timo

**Comment by naderio** [comment]
well, try this until `.once()` is implemented

```
const SocketIO = require('nativescript-socket.io');

SocketIO.Socket.prototype.once = function(event, fn){
  function on() {
    this.off(event, on);
    fn.apply(this, arguments);
  }
  on.fn = fn;
  this.on(event, on);
  return this;
};
```

**Comment by naderio** [comment]
probably `Emitter#listeners(event)` and `Emitter#hasListeners(event)` need to be implemented as well

**Comment by fuleshu** [comment]
thanks for your fast reply.
I am using typescript and unfortunately typescript does not compile it:
`app/utils/feathers.service.ts(27,16): error TS2339: Property 'fn' does not exist on type '() => void'.`
This is the point where my javascript/typescript understanding is not deep enough...

**Comment by naderio** [comment]
that's expected with TypeScript
try removing the `on.fn = fn;` instruction then .. or change it to  `(<any>on).fn = fn;`

**Comment by naderio** [comment]
@fuleshu check latest on master please

**Comment by fuleshu** [comment]
Thanks for the fast fix! 
Unfortunately I did not manage to test it because I just couldn't get the master version running in my app. Using the tns plugin installer installs version 0.3.0. I tried several ways I found in the net to get the latest github version into the node_modules, also tried cloning the repro there directly. But non of them would get the code working in my app :(

**Comment by naderio** [comment]
`npm install naderio/nativescript-socket.io#master` then `tns run android` or `tns run ios`
I've run the demo app successfully

**Comment by naderio** [comment]
@fuleshu recheck no please

**Comment by fuleshu** [comment]
when I run:
`npm install naderio/nativescript-socket.io#master`
it only create the following files in the `nativescript-socket.io` directory:
```
d----        01.12.2016     15:54            platforms
-a---        01.12.2016     15:54         84 .npmignore
-a---        01.12.2016     15:54        790 common.d.ts
-a---        01.12.2016     15:54        112 helpers.d.ts
-a---        01.12.2016     15:54       1234 LICENSE.md
-a---        01.12.2016     15:54      14792 package.json
-a---        01.12.2016     15:54       9783 README.md
-a---        01.12.2016     15:54        730 socket.d.ts
```
but when I run `npm install nativescript-socket.io` it installs:
```
d----        01.12.2016     16:12            platforms
-a---        01.12.2016     16:12         75 .npmignore
-a---        01.12.2016     16:12        773 common.d.ts
-a---        01.12.2016     16:12       1381 common.js
-a---        01.12.2016     16:12       2134 helpers.android.js
-a---        01.12.2016     16:12        110 helpers.d.ts
-a---        01.12.2016     16:12       1566 helpers.ios.js
-a---        01.12.2016     16:12       1210 LICENSE.md
-a---        01.12.2016     16:12       2886 package.json
-a---        01.12.2016     16:12       9215 README.md
-a---        01.12.2016     16:12       6229 socket.android.js
-a---        01.12.2016     16:12        706 socket.d.ts
-a---        01.12.2016     16:12       5601 socket.ios.js
```
But I see that you changes the default version, so running the later now installs 0.4.0 and not 0.3.0 anymore.
So I installed it using `tns plugin add nativescript-socket.io` again and now that it uses 0.4.0 everything works fine.
Featherjs now runs without problems.
Thanks a lot!!!
